## Now You Code 2: Syracuse Crime Data

In this second now you code you will explore the plot.ly engine in detail using Syracuse, NY FBI crime data.

In [1]:
import plotly.plotly as py    
import plotly.graph_objs as go  
import cufflinks as cf
import pandas as pd

In [2]:
crime = pd.read_csv('https://raw.githubusercontent.com/mafudge/datasets/master/crime/syracuse-crime-data-1985-2012.csv')
crime.sample(10)

,Year,Months,Population,Violent crime total,Murder and nonnegligent Manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime total,Burglary,...,Violent Crime rate,Murder and nonnegligent manslaughter rate,Forcible rape rate,Robbery rate,Aggravated assault rate,Property crime rate,Burglary rate,Larceny-theft rate,Motor vehicle theft rate,Unnamed: 21
24,2009,12,137208,1343,18,70,403,852,5779,1946,...,978.8,13.1,51.0,293.7,621.0,4211.9,1418.3,2547.2,246.3,NaN
4,1989,12,154960,1360,13,113,488,746,10290,3502,...,877.6,8.4,72.9,314.9,481.4,6640.4,2259.9,4016.5,364.0,NaN
23,2008,12,138211,1366,24,71,419,852,6165,1938,...,988.3,17.4,51.4,303.2,616.4,4460.6,1402.2,2695.2,363.2,NaN
16,2001,12,147577,1562,15,42,567,938,7905,1810,...,1058.4,10.2,28.5,384.2,635.6,5356.5,1226.5,3519.5,610.5,NaN
6,1991,12,164474,1559,13,86,608,852,11148,3328,...,947.9,7.9,52.3,369.7,518.0,6778.0,2023.4,4321.7,432.9,NaN
9,1994,12,163374,1234,16,58,582,578,9409,2945,...,755.3,9.8,35.5,356.2,353.8,5759.2,1802.6,3476.7,479.9,NaN
0,1985,12,164659,1013,12,80,551,370,11037,3741,...,615.2,7.3,48.6,334.6,224.7,6702.9,2272.0,4172.3,258.7,NaN
12,1997,12,159610,1430,15,55,586,774,9075,2388,...,895.9,9.4,34.5,367.1,484.9,5685.7,1496.1,3731.6,458.0,NaN
3,1988,12,160353,1366,16,103,537,710,10894,3649,...,851.9,10.0,64.2,334.9,442.8,6793.8,2275.6,4182.6,335.5,NaN
17,2002,12,148712,1519,23,43,551,902,8272,1930,...,1021.4,15.5,28.9,370.5,606.5,5562.4,1297.8,3402.5,862.1,NaN

In [3]:
# Make a line plot of population over the years, using cufflinks crime.iplot()
# set the titles on x "Year, Y "Population" and cart title " Syracuse Population" 
# TODO: replace the ???? with appropriate values to render the chart
crime.iplot(kind = 'scatter', x = 'Year', y = 'Population', title='Syracuse Population',xTitle='Year',yTitle='Population')

In [4]:
# Now plot the same thing using plot.ly without cufflinks, again filling in the templates. Using plot.ly takes more effort but
# you have more control / flexibility over how the plots are rendered.
plot_data = [
    go.Scatter(x=crime['Year'], y=crime['Population'], mode="lines+markers", name="Syracuse Population", marker=dict(color='red')),
]

py.iplot({ 'data': plot_data,
            'layout': {
               'title': 'Syracuse Population',
               'xaxis': {
                 'title': 'Year'},
               'yaxis': {
                'title': 'Population'}
        }})

In [5]:
# Now create a line plot of "Robbery rate" versus "Motor vehicle theft rate" over time.
# NOTE: you will need two series in your plot_data 
plot_data = [
    go.Scatter(x=crime['Year'], y=crime['Robbery rate'], mode="lines+markers", name="Robbery rate", marker=dict(color='red')),
    go.Scatter(x=crime['Year'],y=crime['Motor vehicle theft rate'], mode="lines+markers", name="Motor vehicle theft rate", marker=dict(color='blue')),
]
py.iplot({ 'data': plot_data,
            'layout': {
               'title': 'Crime Rate',
               'xaxis': {
                 'title': 'Year'},
               'yaxis': {
                'title': 'Rate'}
        }})

In [10]:

Crimedoc=['Year','Months','Population''Violent crime total','Murder and nonnegligent Manslaughter','Forcible rape',
          'Robbery','Aggravated assault','Property crime total','Burglary','Violent Crime rate''Murder and nonnegligent',
          'manslaughter rate','Forcible rape rate','Robbery rate','Aggravated assault rate','Property crime rate',
          'Burglary rate','Larceny-theft rate','Motor vehicle theft rate','Unnamed: 21']
Crimedoc_handler=[]
for i in range(len(Crimedoc)):
    print(Crimedoc[i])
Crime_metric=input("Enter a crime metric here")
if Crimedoc.count(Crime_metric)==1:
    plot_data=[
    go.Scatter(x=crime['Year'],y=crime[Crime_metric],mode="lines+markers",name="rate", marker=dict(color='red'))

    ]
    print_out=py.iplot({ 'data': plot_data,
                'layout': {
                   'title': 'Crime Rate',
                   'xaxis': {
                     'title': 'Year'},
                   'yaxis': {
                    'title': 'Rate'}
            }})

else:
    print("That's not a crime metric ")
    print_out=None
print_out

Year
Months
PopulationViolent crime total
Murder and nonnegligent Manslaughter
Forcible rape
Robbery
Aggravated assault
Property crime total
Burglary
Violent Crime rateMurder and nonnegligent
manslaughter rate
Forcible rape rate
Robbery rate
Aggravated assault rate
Property crime rate
Burglary rate
Larceny-theft rate
Motor vehicle theft rate
Unnamed: 21
Enter a crime metric hereRobbery